-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 21:27:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `data_nasc` DATE NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `id_turmas` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `turmas_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_turmas`),
  INDEX `fk_vendas_clientes1_idx` (`turmas_id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`turmas_id_turma`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `diciplinas` VARCHAR(120) NOT NULL,
  `alunos_id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_cursos_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_has_turmas` (
  `cursos_id_curso` INT NOT NULL,
  `turmas_id_turmas` INT NOT NULL,
  PRIMARY KEY (`cursos_id_curso`, `turmas_id_turmas`),
  INDEX `fk_cursos_has_turmas_turmas1_idx` (`turmas_id_turmas` ASC) VISIBLE,
  INDEX `fk_cursos_has_turmas_cursos1_idx` (`cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_turmas_cursos1`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `mydb`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_turmas_turmas1`
    FOREIGN KEY (`turmas_id_turmas`)
    REFERENCES `mydb`.`turmas` (`id_turmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
